// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjFsFGAMQ0nw7FFPSskLe5IUtb20C_Ib0',
    appId: '1:898829316502:web:924ac43e6e675edaffadb7',
    messagingSenderId: '898829316502',
    projectId: 'shasanmitra-2e6b2',
    authDomain: 'shasanmitra-2e6b2.firebaseapp.com',
    storageBucket: 'shasanmitra-2e6b2.firebasestorage.app',
    measurementId: 'G-2EDVH4T55T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlFZOR6qOAqPm8nT8cYfgSqeXKN4yAyUg',
    appId: '1:898829316502:android:9bd76b5695f22410ffadb7',
    messagingSenderId: '898829316502',
    projectId: 'shasanmitra-2e6b2',
    storageBucket: 'shasanmitra-2e6b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBExgruitlbhAcgd1H_bvol7BMTlykwRlQ',
    appId: '1:898829316502:ios:179502948a3e0d57ffadb7',
    messagingSenderId: '898829316502',
    projectId: 'shasanmitra-2e6b2',
    storageBucket: 'shasanmitra-2e6b2.firebasestorage.app',
    iosBundleId: 'com.example.shasanmitra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBExgruitlbhAcgd1H_bvol7BMTlykwRlQ',
    appId: '1:898829316502:ios:179502948a3e0d57ffadb7',
    messagingSenderId: '898829316502',
    projectId: 'shasanmitra-2e6b2',
    storageBucket: 'shasanmitra-2e6b2.firebasestorage.app',
    iosBundleId: 'com.example.shasanmitra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjFsFGAMQ0nw7FFPSskLe5IUtb20C_Ib0',
    appId: '1:898829316502:web:f9a75c7862ba8f84ffadb7',
    messagingSenderId: '898829316502',
    projectId: 'shasanmitra-2e6b2',
    authDomain: 'shasanmitra-2e6b2.firebaseapp.com',
    storageBucket: 'shasanmitra-2e6b2.firebasestorage.app',
    measurementId: 'G-79G7E738JF',
  );
}
